# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('tab', models.CharField(max_length=255)),
                ('functions', models.CharField(max_length=255)),
                ('data', models.TextField(max_length=255)),
                ('updatedBy', models.CharField(max_length=255)),
                ('permissions', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='date created')),
            ],
        ),
    ]
